<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HASSEN-HP" failures="4" tests="4" name="Free CRM PRO Tests" time="33.713" errors="0" timestamp="2022-08-18T17:12:33 EDT">
  <testcase classname="com.TestCases.HomePageTest" name="HomePageTitleTest" time="0.012">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.TestCases.HomePageTest.HomePageTitleTest(HomePageTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- HomePageTitleTest -->
  <testcase classname="com.TestCases.HomePageTest" name="CRMLogoImageTest" time="0.003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.TestCases.HomePageTest.CRMLogoImageTest(HomePageTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CRMLogoImageTest -->
  <testcase classname="com.TestCases.HomePageTest" name="verifyUserNameTest" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.TestCases.HomePageTest.verifyUserNameTest(HomePageTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserNameTest -->
  <testcase classname="com.TestCases.FourTest" name="testFour" time="3.016">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestCases.FourTest.testFour(FourTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
</testsuite> <!-- Free CRM PRO Tests -->
