<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-21T18:36:32 EDT" name="Free CRM PRO Automation Test Suite" finished-at="2022-08-21T18:38:13 EDT" duration-ms="100675">
    <groups>
    </groups>
    <test started-at="2022-08-21T18:36:32 EDT" name="CRM PRO LandingPage" finished-at="2022-08-21T18:38:13 EDT" duration-ms="100675">
      <class name="com.TestCases.FourTest">
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:36:32 EDT" name="setUP" finished-at="2022-08-21T18:37:08 EDT" duration-ms="35847" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="testFour()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:08 EDT" name="testFour" description="This is a description for testFour" finished-at="2022-08-21T18:37:12 EDT" duration-ms="3604" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.TestCases.FourTest.testFour(FourTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:12 EDT" name="tearDown" finished-at="2022-08-21T18:37:15 EDT" duration-ms="3085" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:15 EDT" name="setUP" finished-at="2022-08-21T18:37:34 EDT" duration-ms="18182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="verifyBrokenImages()[pri:1, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:34 EDT" name="verifyBrokenImages" description="Find broken images on a web page" finished-at="2022-08-21T18:37:43 EDT" duration-ms="9957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBrokenImages -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:43 EDT" name="tearDown" finished-at="2022-08-21T18:37:50 EDT" duration-ms="6143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:37:50 EDT" name="setUP" finished-at="2022-08-21T18:38:09 EDT" duration-ms="19658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="verifyBrokenlinks()[pri:2, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:38:09 EDT" name="verifyBrokenlinks" description="Find broken Links on a web page" finished-at="2022-08-21T18:38:09 EDT" duration-ms="4" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.Utils.Brokenlinks.myBrokenLinks(Brokenlinks.java:25)
at com.TestCases.FourTest.verifyBrokenlinks(FourTest.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBrokenlinks -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.TestCases.FourTest@48793bef]" started-at="2022-08-21T18:38:10 EDT" name="tearDown" finished-at="2022-08-21T18:38:13 EDT" duration-ms="3233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.TestCases.FourTest -->
    </test> <!-- CRM PRO LandingPage -->
  </suite> <!-- Free CRM PRO Automation Test Suite -->
</testng-results>
